name: Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Build and push to gh-pages branch
        run: |

          git config --global user.name 'CI bot'
          git config --global user.email 'letientai299@bot.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

          git checkout gh-pages --force
          find . -type d | grep -vE '(\.git|\.\.|\.)' | xargs rm -rf

          npm install
          git checkout master .
          make index

          find . -type f | grep -vE '\.(git|json|html|css|js|png|webp)' | xargs rm
          find . -type f | grep -E '\.(json|html|css|js|png|webp)' | xargs git add -f

          git commit -m "Generate index.html from ${GITHUB_SHA}" --allow-empty
          git push

